/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AppVoteRouteImport } from './routes/_app.vote'
import { Route as AppTimelineRouteImport } from './routes/_app.timeline'
import { Route as AppIdeasRouteImport } from './routes/_app.ideas'
import { Route as AppDecisionRouteImport } from './routes/_app.decision'
import { Route as AppEpisodeEpisodeIdRouteImport } from './routes/_app.episode.$episodeId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVoteRoute = AppVoteRouteImport.update({
  id: '/vote',
  path: '/vote',
  getParentRoute: () => AppRoute,
} as any)
const AppTimelineRoute = AppTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => AppRoute,
} as any)
const AppIdeasRoute = AppIdeasRouteImport.update({
  id: '/ideas',
  path: '/ideas',
  getParentRoute: () => AppRoute,
} as any)
const AppDecisionRoute = AppDecisionRouteImport.update({
  id: '/decision',
  path: '/decision',
  getParentRoute: () => AppRoute,
} as any)
const AppEpisodeEpisodeIdRoute = AppEpisodeEpisodeIdRouteImport.update({
  id: '/episode/$episodeId',
  path: '/episode/$episodeId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/decision': typeof AppDecisionRoute
  '/ideas': typeof AppIdeasRoute
  '/timeline': typeof AppTimelineRoute
  '/vote': typeof AppVoteRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/episode/$episodeId': typeof AppEpisodeEpisodeIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/decision': typeof AppDecisionRoute
  '/ideas': typeof AppIdeasRoute
  '/timeline': typeof AppTimelineRoute
  '/vote': typeof AppVoteRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/': typeof AppIndexRoute
  '/episode/$episodeId': typeof AppEpisodeEpisodeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/decision': typeof AppDecisionRoute
  '/_app/ideas': typeof AppIdeasRoute
  '/_app/timeline': typeof AppTimelineRoute
  '/_app/vote': typeof AppVoteRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_app/': typeof AppIndexRoute
  '/_app/episode/$episodeId': typeof AppEpisodeEpisodeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/decision'
    | '/ideas'
    | '/timeline'
    | '/vote'
    | '/auth/callback'
    | '/episode/$episodeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/decision'
    | '/ideas'
    | '/timeline'
    | '/vote'
    | '/auth/callback'
    | '/'
    | '/episode/$episodeId'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/decision'
    | '/_app/ideas'
    | '/_app/timeline'
    | '/_app/vote'
    | '/auth/callback'
    | '/_app/'
    | '/_app/episode/$episodeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/vote': {
      id: '/_app/vote'
      path: '/vote'
      fullPath: '/vote'
      preLoaderRoute: typeof AppVoteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/timeline': {
      id: '/_app/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof AppTimelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ideas': {
      id: '/_app/ideas'
      path: '/ideas'
      fullPath: '/ideas'
      preLoaderRoute: typeof AppIdeasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/decision': {
      id: '/_app/decision'
      path: '/decision'
      fullPath: '/decision'
      preLoaderRoute: typeof AppDecisionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/episode/$episodeId': {
      id: '/_app/episode/$episodeId'
      path: '/episode/$episodeId'
      fullPath: '/episode/$episodeId'
      preLoaderRoute: typeof AppEpisodeEpisodeIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDecisionRoute: typeof AppDecisionRoute
  AppIdeasRoute: typeof AppIdeasRoute
  AppTimelineRoute: typeof AppTimelineRoute
  AppVoteRoute: typeof AppVoteRoute
  AppIndexRoute: typeof AppIndexRoute
  AppEpisodeEpisodeIdRoute: typeof AppEpisodeEpisodeIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDecisionRoute: AppDecisionRoute,
  AppIdeasRoute: AppIdeasRoute,
  AppTimelineRoute: AppTimelineRoute,
  AppVoteRoute: AppVoteRoute,
  AppIndexRoute: AppIndexRoute,
  AppEpisodeEpisodeIdRoute: AppEpisodeEpisodeIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
